server:
  port: 8082
  servlet:
    context-path: /pagamento
    
    
spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      diaalect: org.hibernate.dialect.MySQL8Dialect
      
  jmx:
    enabled: false
  datasource:
      url: jdbc:mysql://localhost:3306/pagamento?allowPublicKeyRetrieval=true&sslModel=DISABLED&useSSL=false&serverTimezone=UTC
#      jdbc:mysql://localhost:3306/crud?serverTimezone=GMT-6
      username: root
      password: 
